version: "3"

services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=apisolid
    ports:
      - "5432:5432"
